create table products (ID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(255), Price DECIMAL(10,2),Image VARCHAR(255),Description TEXT);
CREATE TABLE Users ( ID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(255) NOT NULL, Email VARCHAR(255) UNIQUE NOT NULL);
create table blogs (ID INT AUTO_INCREMENT PRIMARY KEY, Title Varchar(255),Content TEXT, AuthorID INT,CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP, Status ENUM('published', 'archived') NOT NULL, FOREIGN KEY (AuthorID) REFERENCES Users(ID) );
